#!/usr/bin/python
import pigpio
import time
#
pi = pigio.pi() 

pi.set_mode(9,pigpio.OUTPUT) #Motor 1 (left) pwm D1 gpio 9
pi.set_mode(25,pigpio.OUTPUT) #Motor 1 (left) pwm D2 gpio 25  

pi.set_mode(11,pigpio.OUTPUT) #Motor 2 (right) pwm D1 gpio 11
pi.set_mode(8,pigpio.OUTPUT) #Motor 2 (right) pwm D2 gpio 8   

pi.set_PWM_dutycycle(9,  64) # Motor 1 D1 gira 1/4
pi.set_PWM_dutycycle(25,  0)# Motor 1 D2 gira 1/4

pi.set_PWM_dutycycle(11,  64) # Motor 2 D1 gira 1/4
pi.set_PWM_dutycycle(8,  0) #  Motor 2 D2 gira 1/4 

time.sleep(5) # Espera 5 segundos 

pi.set_PWM_dutycycle(9,  0) # Motor 1 D1 para
pi.set_PWM_dutycycle(25,  0)# Motor 1 D2 para

pi.set_PWM_dutycycle(11,  0) # Motor 2 D1 para
pi.set_PWM_dutycycle(8,  0) #  Motor 2 D2 para

pi.stop()                    
